### ISSUE TITLE
Low Battery information at start in Eve

### ISSUE THREAD

**Issue by GSanCap** [hannseman/homebridge-mi-hygrothermograph#11]
Hi dude, when the homebridge instance with this plugin restart, for example, when you add a new hygrothermograph to the config.json, in the Eve App you can see a couple of minutes the "Low Battery" icon associated to the accesossrie. In the Home App don´t show the Battery Information at all, if you wait 2 minutes (or something like that) the info appears again.
Maybe you can cache Battery information using Homebridge persistence capabilities, the first Battery info that the accessory shows is the cached one, meanwhile the plugin do whatever do ;) for take the correct value (battery levels don't change quickly, i think that it's ok show a cached info when the plugin brings to life after a restart).

Regards

**Comment by hannseman** [comment]
Hi! Yes I've noticed that too but haven't really given it some thought since it's not that often you actually restart Homebridge. I don't think it's a good idea to introduce the complexity of managing a cache in a simple plugin as this just to fix this small issue. 

If this was happening in the actual Home-app maybe one could argue for a fix but until then I think we'll do with just a notice in the README. Added this in 3933561f739f7f3a3cdc74e7aac79fa15667c1c2.

Thanks!
