### ISSUE TITLE
Guide: Install LYWSD03MMC in macOS 

### ISSUE THREAD

**Issue by MontroseSt** [hannseman/homebridge-mi-hygrothermograph#127]
I had problems receiving bluetooth data from the LYWSD03MMC on a MacBook with macOS Big Sur and Homebridge being installed. So I wanted to share my experience here

1. Install [Xcode](https://apps.apple.com/us/app/xcode/id497799835?mt=12)
2. install the [homebridge-mi-hygrothermograph plugin](https://www.npmjs.com/package/homebridge-mi-hygrothermograph). When using the [Homekit UI plugin](https://www.npmjs.com/package/homebridge-config-ui-x) noble will automatically be installed
3. Here comes the important part: In macOS got to Preferences -> Security & Privacy -> Bluetooth and allow "node" bluetooth access. In my case node was located in usr/local/include/
<img width="780" alt="Screen Shot 2020-12-27 at 2 48 19 PM" src="https://user-images.githubusercontent.com/5749697/103178723-78235900-4853-11eb-9101-083209e36bac.png">
4. Reboot Homebridge and you should receive data from the hygrothermograph from now on (check Homebridge logs  with debug mode enabled)

The above steps were required to get the plugin up and running in Big Sur. 

Catalina does not have any Bluetooth settings in  "Security & Privacy". However, to make the plugin receive data in Catalina I needed to reset my bluetooth settings (Press Option+Shift and clíck on Bluettoth Icon in the  menu bar -> Select "Debug" in drop-down menu ->  "Reset Bluetooth"

**Comment by hannseman** [comment]
Many thanks for this guide! I'm going to close this issue as it'll be easier for me to have as few issue open as possible. I've added a link to this issue in the README: https://github.com/hannseman/homebridge-mi-hygrothermograph#macos

**Comment by kahuitel** [comment]
Hello,

It seems that Apple broken something since Monterey, Homebridge wont scan for devices.


Here is my conf : 

`{
    "bridge": {
        "name": "Homebridge 9657",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51220,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [
        {
            "name": "Temperature & Humidity",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": false,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "accessory": "Hygrotermograph",
            "_bridge": {
                "username": "xx:xx:xx:xx:xx:xx",
                "port": 54243
            }
        }
}`

Here is my log : 

`[1/6/2022, 11:45:34 AM] Homebridge v1.3.9 (HAP v0.9.8) (Homebridge 9657) is running on port 51220.
[1/6/2022, 11:45:34 AM] [Temperature & Humidity] Launched child bridge with PID 3385
[1/6/2022, 11:45:36 AM] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[1/6/2022, 11:45:36 AM] [Temperature & Humidity] Loaded homebridge-mi-hygrothermograph v3.1.0 child bridge successfully
[1/6/2022, 11:45:36 AM] [Temperature & Humidity] address option is not set. When running multiple sensors this will cause interference. See README for instructions.
[1/6/2022, 11:45:36 AM] [Temperature & Humidity] Initialized accessory
[1/6/2022, 11:45:36 AM] Publishing bridge accessory (name: Temperature & Humidity, publishInfo: {
  username: 'xx:xx:xx:xx:xx:xx',
  port: 54243,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[1/6/2022, 11:45:36 AM] Homebridge v1.3.9 (HAP v0.9.8) (Temperature & Humidity) is running on port 54243.
[1/6/2022, 11:45:36 AM] [Temperature & Humidity] Start scanning.
[1/6/2022, 11:45:36 AM] [Temperature & Humidity] Started scanning.`

Then nothing happens.

See related article here : [https://giters.com/abandonware/noble/issues/225](url)

**Comment by hannseman** [comment]
@kahuitel yes this is a known issue. Follow https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/163 for any updates.
