### ISSUE TITLE
Name not show in accessory

### ISSUE THREAD

**Issue by GSanCap** [hannseman/homebridge-mi-hygrothermograph#3]
Hi, excellent work! i have an issue, the name provided in the accessory declaration are not assigned in the Homekit created accessory, i have 2 Hygromethers, my config.json snippet is:

`{
      "accessory": "Hygrotermograph",
      "name":      "HyHabita",
      "address":   "4c:65:a8:d0:43:35"
    },
    {
      "accessory": "Hygrotermograph",
      "name":      "HyBeta",
      "address":   "4c:65:a8:d2:a1:79"
    }`

The plugin creates 4 accessories but the serial is the same for all, and shares the battery level information.

Regards

**Comment by hannseman** [comment]
Thank you!

Yes currently the names of the accessories are just for labels in your config.json. The names “Humidity” and “Temperature” are hard coded. It should be pretty easy to add support for custom names in the config but since it’s very easy to set custom names in the Home-app I haven’t bothered with it yet.

Regarding you seeing the same battery info, don’t you think that your two sensors simply have the same battery level? The temperature and humidity accessories in the Home-app exposed from the same sensor are of course expected the share the same battery level. 

If you see different temperature/humidity values it shouldn’t be possible for the battery level value to be from the other accessory. I have multiple sensors running and they show different battery levels. Note that these devices are very energy efficient and you’ll not see the value changing very often.

Regarding you seeing the same serial number is because it is hard coded as the model number. That’s a fault by me and will be changed the be present in the model field instead. The value for the serial field could maybe be the address of the sensor.

If you still think that you are getting the wrong values please turn on debug logging in Homebridge. You’ll see the string “Peripheral discovered” with some data followed by the string “Battery level”. Paste that output here for both sensors.

- Hannes

**Comment by GSanCap** [comment]
Thanks for the Quick Response! You can use the name + "T" and "H" for naming the accessories, for example, and you can use the BLE MAC Address as Serial number for easy recon ;)
About the battery values i will query the hygros later with gatttool and compare the values obtained with "char-read-hnd 0x0018" in interactive mode.

Regards

**Comment by hannseman** [comment]
Wow just saw the wall of text in my previous reply. Sorry about that. Did reply from email so the formatting must’ve disappeared.

I don’t think it’s a good idea to add suffixes to the name and use that on the Humidity and Temperature Characteristics. The name set on those is what is recognized by Siri so you’ll want something relevant and easy to pronounce. 

The best approach is probably to add new parameters in the config for setting each name.

Regarding the serial number it’s just as you’re saying a good idea to use the device address.

**Comment by hannseman** [comment]
I've split up this issue into two separate issues for tracking the configuration of the characteristic names and having unique serial numbers. See #4 and #5.

If you're having trouble with the connection being cut when using gatttool you can look into the service data in the advertising packets. The battery data is in the packet with service data which has length of 15 bytes. The last byte is the battery value.

I was having lots of trouble with connections being dropped after a few seconds by these devices. It looks like they run some kind of authentication which I never could figure out.

**Comment by GSanCap** [comment]
About the names, in this case, temperature and humidity in homekit you don't use the sensor name for asking about the service, you use the room name for referencing like "Hey siri what is the temperature of the kichen?" or "What is the humidity if the bathroom?" you don't ask about the sensor name, you use the name of the service that provides ;)

Regards

**Comment by hannseman** [comment]
Ah yes you are correct! Misread the documentation there. Anyway you can now customise the accessory names through config.json.

I'm closing this issue but if you notice any weird stuff regarding the battery levels please open a new issue. 

Thank you!
